suffix: indoor3d
output: ./save
seed: 10
linear_quantization: False
preserve_ratio: 0.5
float_bit: 32
is_pruned: False
rmsize: 128
finetune_flag: True
finetune_lr: 0.001
finetune_gamma: 0.8
finetune_epoch: 1
min_bit: 2
max_bit: 4
work_dir: save
# DDPG
hidden1: 300
hidden2: 300
lr_c: 1e-3
lr_a: 1e-4
warmup: 20
discount: 1.0
bsize: 64
rmsize: 128
window_length: 1
tau: 0.01
init_delta: 0.5
delta_decay: 0.99
n_update: 1
init_w: 0.0003
epsilon: 50000
init_delta: 0.5
