batch_size: 16
epoch: 200
learning_rate: 1e-3
gpu: 0
num_point: 1024
optimizer: Adam
weight_decay: 1e-4
normal: True
lr_decay: 0.5
step_size: 20
num_category: 16
num_part: 50
num_workers: 8
train_episode: 600
output: ./save
warmup: 5
fp16: True

model: 
  nneighbor: 16
  nblocks: 4
  transformer_dim: 512
  name: PointTransformer

work_dir: log/partseg/PointTransformer
init_delta: 0.5
delta_decay: 0.99
n_update: 1
